### ISSUE TITLE
IPython magic functions generate invalid syntax error.

### ISSUE THREAD

**Issue by Edigiraldo** [codiga/chrome-extension#10]
**Describe the bug**
IPython magic functions generate and invalid syntax error.
**To Reproduce**
1. Open a Jupyter notebook
2. Write some IPython magic function command (For ex. '%pwd')
3. wait for codiga extension to check your code.
4. See syntax error appear.

**Expected behavior**
Not to display that syntax error.

**Screenshots**
![magic functions error](https://i.ibb.co/5YTqQVd/2-IPython-magic-function-error.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser Google Chrome
 - Version 93.0.4577.63

**Comment by juli1** [comment]
@Edigi12Hbtn thanks for the bug report. We are on it!

**Comment by juli1** [comment]
This issue is now fixed.
