### ISSUE TITLE
All variables appear undeclared when they in fact are.

### ISSUE THREAD

**Issue by Edigiraldo** [codiga/chrome-extension#9]
**Describe the bug**
Literally all variables appear as if they were not declared.

**To Reproduce**
1. Load any notebook. (I tested on Tensorflow professional certificate notebook courses from Coursera)
2. Run the notebook.
3. Check the error appearing on any variable you declared including imported libraries.

**Expected behavior**
Variables are expected to appeared declared when program does it.

**Screenshots**
![Os not declared](https://i.ibb.co/c3RpFMP/1a-all-declared-variables-appeared-undeclared.png)
![Os not declared](https://i.ibb.co/VV95TDB/1b-all-declared-variables-appeared-undeclared.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Google Chrome
 - Version: 93.0.4577.63

**Additional context**
It happens to me with **all** variables and documents.

**Comment by juli1** [comment]
@Edigi12Hbtn thanks for reporting this issue. That is actually something we can definitely fix.

@jmromeroeci - it seems that the different blocks do not take into account the previous declarations. We will need to analyze all blocks in one file.

**Comment by jmromeroeci** [comment]
Perfect, it's fixed in the code, now we just have to wait for pushing the update to the Chrome marketplace.
